name: Generate Datas
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Assets Folder
        run: mkdir -p assets

      - name: Generate Snake (Blue Theme)
        uses: Platane/snk@v3
        with:
          github_user_name: thomas4ugust0
          outputs: |
            assets/github-contribution-grid-snake.svg?color_snake=%233D74FF&color_dots=%23ebedf0,%238cb4ff,%235882fa,%231d4ed8,%23172554
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%233D74FF&color_dots=%23161b22,%231e3a8a,%232563eb,%233d74ff,%2360a5fa

      - name: Commit & Push Snake animation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/github-contribution-grid-snake.svg assets/github-contribution-grid-snake-dark.svg
          git commit -m "chore: atualiza cobrinha" || echo "Nenhuma alteração detectada"
          git push
